CREATE TABLE CART
(
    UserID  NUMBER(4) PRIMARY KEY,
    ProductID  NUMBER(4),
    Quantity NUMBER(4),
    CONSTRAINT FK_CHOOSE_USER FOREIGN KEY (UserID) REFERENCES Customer(UserID),
    CONSTRAINT FK_CHOOSE_PRODUCT FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);
