DROP TABLE BROWSE;
DROP TABLE CHECKOUT;
DROP TABLE CHOOSE;
DROP TABLE SELL;
DROP TABLE SHIPMENT;
DROP TABLE USERCOMMENT;


DROP TABLE PARCEL;
DROP TABLE SELLER;
DROP TABLE PRODUCT;
DROP TABLE REVIEW;
DROP TABLE CUSTOMER;
DROP TABLE CART;
DROP TABLE CENTRE;
