-- DROP TABLE BROWSE;
-- DROP TABLE CHECKOUT;
-- DROP TABLE CHOOSE;
-- DROP TABLE SELL;
-- DROP TABLE SHIPMENT;
-- DROP TABLE USERCOMMENT;
--
--
-- DROP TABLE PARCEL;
-- DROP TABLE PRODUCT;
-- DROP TABLE REVIEW;
-- DROP TABLE CUSTOMER;
-- DROP TABLE CART;
-- DROP TABLE CENTRE;
-- DROP TABLE SELLER;

-- Order Cannot change
DROP TABLE PARCEL;
DROP TABLE CHECKOUT;
DROP TABLE CART;
DROP TABLE USERCOMMENET;
DROP TABLE REVIEW;
DROP TABLE PRODUCT;
DROP TABLE CUSTOMER;
DROP TABLE PRODUCT;
DROP TABLE SELLER;
