CREATE TABLE BROWSE
(
    UserID Number(4),
    ProductID NUMBER(4),
    CONSTRAINT FK_BROWSE_CUSTOMER FOREIGN KEY (UserID) REFERENCES CUSTOMER(UserID),
    CONSTRAINT FK_BROWSE_PRODUCT FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);