CREATE TABLE SELL
(
    SellerID  NUMBER(4),
    ProductID NUMBER(4),
    CONSTRAINT FK_SELL_SELLER FOREIGN KEY (SellerID) REFERENCES SELLER(SellerID),
    CONSTRAINT FK_SELL_PRODUCT FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);
