CREATE TABLE SHIPMENT
(
    ParcelID NUMBER(4),
    CentreID NUMBER(4),
    CONSTRAINT FK_SHIPMENT_PARCEL2
    FOREIGN KEY (ParcelID)
    REFERENCES PARCEL(ParcelID),
    CONSTRAINT FK_SHIPMENT_CENTRE2
    FOREIGN KEY (CentreID)
    REFERENCES Centre(CentreID)
);
