CREATE TABLE USERCOMMENT
(
    ReviewID   NUMBER(4) PRIMARY KEY,
    ProductID  NUMBER(4),
    CONSTRAINT FK_COMMENT_REVIEW
    FOREIGN KEY (ReviewID)
    REFERENCES Review(ReviewID),
    CONSTRAINT FK_COMMENT_PRODUCT
    FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID)
);
